# Generated by Django 4.1.7 on 2023-02-28 08:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_num", models.CharField(db_column="flight_num", max_length=24)),
                (
                    "origin_country",
                    models.CharField(db_column="origin_country", max_length=128),
                ),
                (
                    "origin_city",
                    models.CharField(db_column="origin_city", max_length=128),
                ),
                (
                    "origin_code",
                    models.CharField(db_column="origin_code", max_length=24),
                ),
                (
                    "destination_country",
                    models.CharField(db_column="destination_country", max_length=128),
                ),
                (
                    "destination_city",
                    models.CharField(db_column="destination_city", max_length=128),
                ),
                (
                    "destination_code",
                    models.CharField(db_column="destination_code", max_length=24),
                ),
                ("origin_dt", models.DateTimeField(db_column="origin_dt")),
                ("destination_dt", models.DateTimeField(db_column="destination_dt")),
                (
                    "total_seats",
                    models.IntegerField(
                        db_column="total_seats",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "seats_left",
                    models.IntegerField(
                        db_column="seats_left",
                        default=models.IntegerField(
                            db_column="total_seats",
                            validators=[django.core.validators.MinValueValidator(0)],
                        ),
                    ),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(db_column="is_cancelled", default=False),
                ),
                ("price", models.FloatField(db_column="price")),
            ],
            options={
                "db_table": "flights",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seats", models.IntegerField(db_column="seats")),
                ("order_date", models.DateField(db_column="order_date")),
                ("total_price", models.FloatField(db_column="total_price")),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api_app.flight"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
