# Generated by Django 4.1.7 on 2023-02-28 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table="orders",
        ),
    ]
