# Generated by Django 4.1.7 on 2023-02-28 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0003_rename_origin_dt_flight_x_alter_flight_seats_left"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="x",
            new_name="origin_dt",
        ),
    ]
