# Generated by Django 4.1.7 on 2023-02-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0004_rename_x_flight_origin_dt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(auto_created=True, db_column="order_date"),
        ),
    ]
