# Generated by Django 4.1.7 on 2023-03-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0005_alter_order_order_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="flight",
            new_name="flight_id",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(auto_now=True, db_column="order_date", null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.FloatField(blank=True, db_column="total_price", null=True),
        ),
    ]
